yolo_model:

  config_file:
    name: yolov4.cfg
  weight_file:
    name: yolov4.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - person
      - bicycle
      - car
      - motorbike
      - aeroplane
      - bus
      - train
      - truck
      - boat
      - traffic light
      - stop sign
